[global]
index-url = https://nexus.yc.loc/repository/pypi-yc
extra-index-url =
    https://nexus.yc.loc/repository/pypi-yc/simple
    https://nexus.yc.loc/repository/yc-python/simple
trusted-host = nexus.yc.loc
cert = /usr/local/share/ca-certificates/nexus.crt
