"""Initial migration

Revision ID: 445473c61f96
Revises:
Create Date: 2026-04-14 15:11:08.254767+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "445473c61f96"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS licensemanager")
    op.create_table(
        "audit_log_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column(
            "actor_type", sa.String(length=64), server_default="system", nullable=False
        ),
        sa.Column("actor_display_name", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=64), server_default="api", nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.String(length=255), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log_entries")),
        schema="licensemanager",
    )
    op.create_index(
        "ix_audit_log_entries_created_at",
        "audit_log_entries",
        ["recorded_at"],
        unique=False,
        schema="licensemanager",
    )
    op.create_index(
        "ix_audit_log_entries_entity",
        "audit_log_entries",
        ["entity_type", "entity_id"],
        unique=False,
        schema="licensemanager",
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("contact_person_name", sa.String(length=128), nullable=True),
        sa.Column("contact_person_phone", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column(
            "notifications_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "gem_fury_used",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("customer_symbol", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("customer_symbol", name="customersymbol_unique"),
        schema="licensemanager",
    )
    op.create_table(
        "kinds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kinds")),
        schema="licensemanager",
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        schema="licensemanager",
    )
    op.create_table(
        "app_packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.String(length=16), nullable=False),
        sa.Column("binary_name", sa.String(length=128), nullable=False),
        sa.Column("gem_fury_url", sa.String(length=128), nullable=False),
        sa.Column("binary_url", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_packages")),
        sa.UniqueConstraint("version_number", name="versionnumber_unique"),
        schema="licensemanager",
    )
    op.create_table(
        "settings",
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("schema_id", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("modified_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column("modified_by", sa.Text(), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("object_id", name=op.f("pk_settings")),
        schema="licensemanager",
    )
    op.create_index(
        "settings_modified_at_idx",
        "settings",
        [sa.literal_column("modified_at DESC")],
        unique=False,
        schema="licensemanager",
    )
    op.create_index(
        "settings_schema_scope_idx",
        "settings",
        ["schema_id", "scope"],
        unique=False,
        schema="licensemanager",
    )
    op.create_index(
        "settings_value_gin_idx",
        "settings",
        ["value"],
        unique=False,
        schema="licensemanager",
        postgresql_using="gin",
        postgresql_ops={"value": "jsonb_path_ops"},
    )
    op.create_table(
        "licenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("kind_id", sa.UUID(), nullable=True),
        sa.Column("license_count", sa.Integer(), nullable=False),
        sa.Column("license_state", sa.String(length=128), nullable=False),
        sa.Column("license_key", sa.String(length=512), nullable=False),
        sa.Column("license_email", sa.Text(), nullable=False),
        sa.Column("double_send", sa.Boolean(), nullable=False),
        sa.Column("begin_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("end_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("notification_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["licensemanager.customers.id"],
            name=op.f("fk_licenses_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["kind_id"],
            ["licensemanager.kinds.id"],
            name=op.f("fk_licenses_kind_id_kinds"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["licensemanager.products.id"],
            name=op.f("fk_licenses_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_licenses")),
        sa.UniqueConstraint("license_key", name="licensekey_unique"),
        schema="licensemanager",
    )
    op.create_index(
        op.f("ix_licensemanager_licenses_customer_id"),
        "licenses",
        ["customer_id"],
        unique=False,
        schema="licensemanager",
    )
    op.create_index(
        op.f("ix_licensemanager_licenses_kind_id"),
        "licenses",
        ["kind_id"],
        unique=False,
        schema="licensemanager",
    )
    op.create_index(
        op.f("ix_licensemanager_licenses_product_id"),
        "licenses",
        ["product_id"],
        unique=False,
        schema="licensemanager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_licensemanager_licenses_product_id"),
        table_name="licenses",
        schema="licensemanager",
    )
    op.drop_index(
        op.f("ix_licensemanager_licenses_kind_id"),
        table_name="licenses",
        schema="licensemanager",
    )
    op.drop_index(
        op.f("ix_licensemanager_licenses_customer_id"),
        table_name="licenses",
        schema="licensemanager",
    )
    op.drop_table("licenses", schema="licensemanager")
    op.drop_index(
        "settings_value_gin_idx",
        table_name="settings",
        schema="licensemanager",
        postgresql_using="gin",
        postgresql_ops={"value": "jsonb_path_ops"},
    )
    op.drop_index(
        "settings_schema_scope_idx", table_name="settings", schema="licensemanager"
    )
    op.drop_index(
        "settings_modified_at_idx", table_name="settings", schema="licensemanager"
    )
    op.drop_table("settings", schema="licensemanager")
    op.drop_table("app_packages", schema="licensemanager")
    op.drop_table("products", schema="licensemanager")
    op.drop_table("kinds", schema="licensemanager")
    op.drop_table("customers", schema="licensemanager")
    op.drop_index(
        "ix_audit_log_entries_entity",
        table_name="audit_log_entries",
        schema="licensemanager",
    )
    op.drop_index(
        "ix_audit_log_entries_created_at",
        table_name="audit_log_entries",
        schema="licensemanager",
    )
    op.drop_table("audit_log_entries", schema="licensemanager")
    op.execute("DROP SCHEMA IF EXISTS licensemanager")
    # ### end Alembic commands ###
