from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class BaseCamelSchema(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True,
        use_enum_values=False,
    )


class RFC7807Error(BaseCamelSchema):
    """Problem Details for HTTP APIs (RFC 7807 / RFC 9457)."""

    type: str = Field(
        default="about:blank",
        description="A URI reference identifying the problem type",
    )
    title: str = Field(description="Short, human-readable summary of the problem type")
    status: int = Field(description="HTTP status code generated by the origin server")
    detail: str | dict | list | None = Field(
        default=None,
        description="Human-readable explanation specific to this occurrence",
    )
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence",
    )
    request_id: str | None = Field(
        default=None,
        description="Server-assigned request identifier, if available",
    )
